__host__ void ApplyBoundaryCondition (float *Dens, float *Energy, float *Vrad, float *Vtheta, float step);
__host__ void NonReflectingBoundary (float *Dens, float *Energy, float *Vrad);
__host__ void ReduceMean (float *Dens, float *Energy);
__host__ void ReduceCs ();
__host__ void MinusMean (float *Dens, float *Energy);
__host__ void EvanescentBoundary (float *Vrad, float *Vtheta, float *Dens, float *Energy, float step);
__host__ void Cscudamalloc ();
__host__ void Meancudamalloc ();
__host__ void OpenBoundary ();
__host__ Pair ComputeAccel (Force *force, float *Dens, float x, float y, float rsmoothing, float mass);
__host__ void DivisePolarGrid (float *Num, float *Denom, float *Res);
__host__ void InitComputeAccel ();
__host__ void InitComputeAccelDevice ();
__host__ void CorrectVtheta (float *Vtheta, float domega);
__host__ void ApplySubKeplerianBoundary(float *VthetaInt);
