__host__ void FillPolar1DArrays ();
__host__ void InitEuler (double *Dens, double *Energy, double *Vrad, double *Vtheta);
__host__ void Computecudamalloc (double *Energy);
__host__ double ConstructSequence (double *u, double *v, int n);
__host__ void Init_azimutalvelocity_withSG (double *Vtheta);
__host__ int DetectCrash (double *array);
__host__ void ComputePressureField ();
__host__ void ComputeSoundSpeed ();
__host__ void ComputeTemperatureField ();
__host__ void AlgoGas (Force *force, double *Dens, double *Vrad, double *Vtheta, double *Energy, double *Label,
  PlanetarySystem *sys, int iteracion);
__host__ void Substep1 (double *Dens, double *Vrad, double *Vtheta, double dt, int initialization);
__host__ void Substep2 (double dt);
__host__ void Substep3 (double *Dens, double dt);
__host__ void ActualiseGasVrad (double *Vrad, double *VradNew);
__host__ void ActualiseGasVtheta (double *Vtheta, double *VthetaNew);
__host__ void ActualiseGasEnergy (double *Energy, double *EnergyNew);
__host__ void Substep1cudamalloc (double *Vrad, double *Vtheta);
__host__ void FillForcesArrays (PlanetarySystem *sys, double *Dens, double *Energy);
__host__ int ConditionCFL (double *Vrad, double *Vtheta , double DeltaT);
__host__ double CircumPlanetaryMass (double *Dens, PlanetarySystem *sys);
