__host__ void Transport (float *Dens, float *Vrad, float *Vtheta, float *energy, float *label, float dt);
__host__ void OneWindRad (float *Dens, float *Vrad, float *energy, float dt);
__host__ void ComputeLRMomenta ();
__host__ void ComputeExtQty ();
__host__ void ActualiseGasDens (float *DensInt, float *Dens);
__host__ void ComputeStarRad(float *Dens, float *Vrad, float *RhoStar, float dt);
__host__ float VanLeerRadial (float *Vrad, float *Qbase, float dt, int ReturnLost);
__host__ void InitTransportDevice ();
__host__ void InitTransport ();
__host__ void OneWindTheta (float *Dens, float *Vtheta, float *energy, float dt);
__host__ void ComputeAverageThetaVelocities (float *Vtheta, float dt);
__host__ void ComputeResiduals (float *Vtheta, float dt);
__host__ void ComputeConstantResidual (float *Vtheta, float dt);
